/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.analysis.low.level.api.fir;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.analysis.low.level.api.fir.TestGeneratorKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/low-level-api-fir/testData/thisLabelResolve")
@TestDataPath("$PROJECT_ROOT")
public class SourceThisLabelResolveTestGenerated extends AbstractSourceThisLabelResolveTest {
  private void run(String fileName) {
    runTest("analysis/low-level-api-fir/testData/thisLabelResolve/" + fileName);
  }

  @Test
  public void testAllFilesPresentInThisLabelResolve() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/low-level-api-fir/testData/thisLabelResolve"), Pattern.compile("^(.+)\\.(kt)$"), null, true);
  }

  @Test
  @TestMetadata("extensionOnPrimitiveType.kt")
  public void testExtensionOnPrimitiveType() {
    run("extensionOnPrimitiveType.kt");
  }

  @Test
  @TestMetadata("freestandingLambda.kt")
  public void testFreestandingLambda() {
    run("freestandingLambda.kt");
  }

  @Test
  @TestMetadata("freestandingLambdaNamed.kt")
  public void testFreestandingLambdaNamed() {
    run("freestandingLambdaNamed.kt");
  }

  @Test
  @TestMetadata("freestandingLambdaWithExtensionNamed.kt")
  public void testFreestandingLambdaWithExtensionNamed() {
    run("freestandingLambdaWithExtensionNamed.kt");
  }

  @Test
  @TestMetadata("functionWithExtension.kt")
  public void testFunctionWithExtension() {
    run("functionWithExtension.kt");
  }

  @Test
  @TestMetadata("functionWithGenericExtension.kt")
  public void testFunctionWithGenericExtension() {
    run("functionWithGenericExtension.kt");
  }

  @Test
  @TestMetadata("lambda.kt")
  public void testLambda() {
    run("lambda.kt");
  }

  @Test
  @TestMetadata("namedFunctionLiteral.kt")
  public void testNamedFunctionLiteral() {
    run("namedFunctionLiteral.kt");
  }

  @Test
  @TestMetadata("simpleFunction.kt")
  public void testSimpleFunction() {
    run("simpleFunction.kt");
  }
}
